### PR TITLE
Restrict the first transaction of each block to be a reward transaction.

### PR DESCRIPTION
**Pull request by Glacier-Luo**

### CODE REVIEW

**Comment by GalaxySciTech** [comment]
if change `coninbase` to `coinbase`
it will make the blockchain miner issue , they will can not miner by themselves

**Comment by Glacier-Luo** [comment]
> if change `coninbase` to `coinbase` it will make the blockchain miner issue , they will can not mint rewards by themselves
> 
> i mean old version

That's ok, could you just restore it to `coninbase` and merge?

**Comment by GalaxySciTech** [comment]
> > if change `coninbase` to `coinbase` it will make the blockchain miner issue , they will can not mint rewards by themselves
> > i mean old version
> 
> That's ok, could you just restore it to `coninbase` and merge?

i think is not necessarily, in blockchain can be added some compatible for example add the coninbase 
could you add this

**Comment by Glacier-Luo** [comment]
> > > if change `coninbase` to `coinbase` it will make the blockchain miner issue , they will can not mint rewards by themselves
> > > i mean old version
> > 
> > 
> > That's ok, could you just restore it to `coninbase` and merge?
> 
> i think is not necessarily, in blockchain can be added some compatible for example add the coninbase could you add this

You mean we allow both `coninbase` and `coinbase` to be key of reward transaction?

**Comment by GalaxySciTech** [comment]
> > > > if change `coninbase` to `coinbase` it will make the blockchain miner issue , they will can not mint rewards by themselves
> > > > i mean old version
> > > 
> > > 
> > > That's ok, could you just restore it to `coninbase` and merge?
> > 
> > 
> > i think is not necessarily, in blockchain can be added some compatible for example add the coninbase could you add this
> 
> You mean we allow both `coninbase` and `coinbase` to be key of reward transaction?

sure

**Pull request closed without merging**
